### ISSUE TITLE
how to create subproject?

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#10]
Hey  @omarpiani ,how to create subproject?

**Comment by omarpiani** [comment]
Vermis can subdivide issues inside projects in "components". You will find a submenu for that inside a project. When you create an issue you assign it to a component.

You can also subdivide issues in time, or versions with "milestones".

**Comment by zjhxmjl** [comment]
ok,thks,but it can not display "component" when i add new issue,i have to click some project and then add new issue.is there any solution?

**Comment by omarpiani** [comment]
ups, sorry. I lost this message. 
You need to enter clicking the project, where the component is in, from the project list, in order to have, the components, milestones and assegnee in create issue page.

**Comment by zjhxmjl** [comment]
yeah,thks!i mean i should not click the project,but i can get the 
components, milestones and assegnee in create issue page,is there any 
way to get?
now create isssues in dashboard is different from creating issues in 
project?i want to keep them the same,which files need to be modify?
