### ISSUE TITLE
add license in signup page

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#12]
i want to add "read agree license" option when new users register,just like "send me email notifications".
when users click "read agree license", which will pop a window.the new users must agree if they want to register.i can translate the agree license in lang/zh_CN.php, maybe you can understand mine idea.sorry for my poor english.by the way,i want to make the "Username/Displayname...etc box" smaller(see my attachment) ,which css file i can modify?
![2017-03-07-140321_1318x468_scrot](https://cloud.githubusercontent.com/assets/4043922/23644084/610fdbc8-0340-11e7-9c9f-60eff6bbfbdd.png)

**Comment by omarpiani** [comment]
I suggest in app/models/Form/User.php to add a required checkbox for license acceptance and set it required.

After that I suggest to add a jquery modal popup on click on themes/default/scripts/default/users/register.phtml

something like 

http://jsfiddle.net/vandalo/nvZc4/

**Comment by omarpiani** [comment]
I made a branch for you https://github.com/koweb/Vermis/tree/accept_licence

**Comment by zjhxmjl** [comment]
thks very much!

**Comment by omarpiani** [comment]
I merged in master.

I've added a new configuration parameter in config.php in order to manage activation of accept licence flag in register.
Default of sample.config.php is false

```
// Enables in user registration the acceptance of a licence.
// Licence text must be written in row 13 of _vermis/themes/default/scripts/users/register.phtml
 'showRegisterAcceptLicence' => true,
```
