### ISSUE TITLE
error 404 Undefined variable

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#2]
Hi,guy!can you give some help?
![2017-02-16-154327_1364x267_scrot](https://cloud.githubusercontent.com/assets/4043922/23011980/cd994df6-f45e-11e6-8b34-a76a9d591aad.png)
system:fedora 20
php version:PHP 5.5.26 (cli) (built: Jun 11 2015 08:23:07) 
apache:Server version: Apache/2.4.10 (Fedora)

**Comment by omarpiani** [comment]
Hi, in home page?

**Comment by zjhxmjl** [comment]
yes,i follow the install guide and success,but get the error info!

**Comment by omarpiani** [comment]
Set short_open_tag=On in your php.ini.

I will soon release an update in order to resolve this incompatibility.

**Comment by omarpiani** [comment]
New version will work even with  short_open_tag=On.

I hope 🙏 .. can be I missed some opening tag, I tested poorely

**Comment by zjhxmjl** [comment]
yeah,you're right.but i find the layout is wrong.
![2017-02-17-082251_1340x491_scrot](https://cloud.githubusercontent.com/assets/4043922/23047385/760df53c-f4ea-11e6-920d-3d436021d8e7.png)

**Comment by omarpiani** [comment]
Normally happens when you configure wrongly you config.ini when you install in a subdirectory.

For example this is the configuration if your installation is in http://192.168.1.10/vermis/

Don't forget ending slash!
 ```
// The base host with the protocol type.
// For example 'http://localhost' or 'https://your.domain.tld'.
'baseHost'                  => 'http://192.168.1.10',

// The base URI on your host.
// If your vermis installation is available on 
// http://your.domain.tld/some/directory
// then you should set baseUri to '/some/directory/'
// Make sure that you have a slash at the end of URI!
 'baseUri'                   => '/vermis/',
```

**Comment by zjhxmjl** [comment]
thks very much!
