### ISSUE TITLE
About short_open_tag error

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#5]
Hey,guy!
To solve this problem,maybe need to modify these files.
![2017-02-18-074828_1147x108_scrot](https://cloud.githubusercontent.com/assets/4043922/23090691/324cffa0-f5df-11e6-803c-dc15b316441a.png)
![2017-02-18-133623_547x234_scrot](https://cloud.githubusercontent.com/assets/4043922/23090696/44445442-f5df-11e6-83a9-e9b3dacb96d9.png)

**Comment by omarpiani** [comment]
Take a look!
