### ISSUE TITLE
Question about translate 

### ISSUE THREAD

**Issue by zjhxmjl** [koweb/Vermis#6]
Hey,i want to translate with other language,so i change these files,but not success!thks for suggestion!
1,config/config.php
'locale'    => 'zh_CN',
2,app/models/Application.php
line 246, add 'zh_CN'    => 'zh_CN'
![2017-02-20-080958_685x421_scrot](https://cloud.githubusercontent.com/assets/4043922/23108187/6cb2cede-f744-11e6-9304-7bb610d186b2.png)

**Comment by omarpiani** [comment]
in https://github.com/koweb/Vermis/commit/c97b2cf4d1434e0afc3bac6a4f8f4df23dee1739

I successfully translated in Italian.

With this update app is translate with your first browser "Accept language", before he takes first language in $locales array in your "Accept language". 

I need to investigate why config.php is ignored.

I'm glad if you make a PR of your chinese translation!

Regards

**Comment by omarpiani** [comment]
```
// If true then don't detect browser language automatically and use 
// default locale setting. If false then check browser language and
// adjust locale setting. 
 'useFixedLocale'			=> false,
```

ah, was easy.. if you want to disable browser language auto detection set useFixedLocale to true

**Comment by zjhxmjl** [comment]
hey @omarpiani ,i think make button and let user choose the site language better!

**Comment by omarpiani** [comment]
I don't think it's difficult..
Better option is set your language in your user profile.
